import React, { useState } from "react";
import { X } from "lucide-react";

export default function CrudModal({ title, fields, initialValues = {}, onClose, onSubmit, submitLabel = "Save" }) {
  const [values, setValues] = useState(() => Object.fromEntries(fields.map((f) => [f.name, initialValues[f.name] ?? ""])));
  const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  async function submit(e) { e.preventDefault(); const missing = fields.find((f) => f.required && !values[f.name]); if (missing) return setError(`${missing.label} is required.`); try { setSaving(true); await onSubmit(values); } catch (err) { setError(err?.response?.data?.message || err.message || "Something went wrong."); } finally { setSaving(false); } }
  return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/40 p-4"><section role="dialog" aria-modal="true" aria-label={title} className="w-full max-w-md rounded-xl bg-white shadow-xl"><header className="flex items-center justify-between border-b px-5 py-4"><h2 className="text-lg font-bold text-gray-800">{title}</h2><button aria-label="Close" type="button" onClick={onClose} className="text-gray-400 hover:text-gray-600"><X size={20} /></button></header><form onSubmit={submit} className="space-y-4 px-5 py-4">{fields.map((f) => <label className="block text-sm font-medium text-gray-600" key={f.name}>{f.label}{f.required && <span className="text-red-500"> *</span>}{f.type === "select" ? <select value={values[f.name]} onChange={(e) => setValues({ ...values, [f.name]: e.target.value })} className="mt-1 block w-full rounded-lg border px-3 py-2"><option value="">Select…</option>{f.options.map((opt) => <option key={opt}>{opt}</option>)}</select> : <input type={f.type || "text"} step={f.type === "number" ? "any" : undefined} value={values[f.name]} onChange={(e) => setValues({ ...values, [f.name]: e.target.value })} className="mt-1 block w-full rounded-lg border px-3 py-2" />}</label>)}{error && <p role="alert" className="rounded-lg bg-red-50 px-3 py-2 text-sm text-red-600">{error}</p>}<footer className="flex justify-end gap-2 pt-2"><button type="button" onClick={onClose} className="rounded-lg px-4 py-2 text-gray-600 hover:bg-gray-100">Cancel</button><button disabled={saving} className="rounded-lg bg-blue-600 px-4 py-2 font-medium text-white hover:bg-blue-700 disabled:opacity-60">{saving ? "Saving…" : submitLabel}</button></footer></form></section></div>;
}
